### PR TITLE
[WIP] Create unit tests with jest

### PR DESCRIPTION
**Pull request by nicholaschuayunzhi**
Currently working on unit tests with jest. This is just a very basic attempt. I made my own mock file system so there may be **alot** of bugs. But with the system I believe we can keep track on what files are built.

I'm also attempting to mock out the `fs-extra-promise` and `walk-sync` so that we don't write/read from disk.

Rationale for using jest is:
* comes shipped with mocking
* by Facebook so it *should be* maintained
* faster than mocha (which does not come with mocking)

Things to note:
* Every module you want to mock needs a `__mocks__` folder in the same directory as the module (except node_modules)
* I'm using `path` module to resolve paths instead of mocking.\
* I can't accurately copy directories and their contents with my system. problem arises when copying assets. I can tell that the directory is copied but I don't know what the sub files/directories are.
* I'm not sure if I'm doing things right, and I'm not sure what items to test for. Do let me know.

### CODE REVIEW

**Comment by nicholaschuayunzhi** [comment]
I have added some comments in https://github.com/MarkBind/markbind-cli/pull/28/commits/64b2e9a38ca45fb4bc7a8eff03ee513be34bb8a5. I'm not very sure about my naming choice so do let me know if arguments/explanation/method names can be worded better. Thanks!

**Comment by danielbrzn** [comment]
I think this is a good start to ensuring Markbind is sufficiently covered by tests. 

However, would it be better to use existing packages for mock file systems such as [mock-fs](https://github.com/tschaub/mock-fs)?

**Comment by nicholaschuayunzhi** [comment]
Hi @danielbrzn, I've looked into those mock file systems and actually tried to implement it with no success. So i decided to stick to my solution for now. It also adds another dependency to our project. However, using a existing, well written mock file system will be less buggy. Just that we still have to implement our own code as mock-fs, [memfs](https://github.com/streamich/memfs) does not implement `fs-extra` and `fs-extra-promise` methods. I think I can try to get it to work again later. For now my focus is to mock `Page`, `Site`, and `Markbind`.

**Comment by nicholaschuayunzhi** [comment]
I've updated the test to use memfs instead as following all the errors specified in the `fs` docs is too tedious/risky.

**Comment by acjh** [comment]
Moved to MarkBind/markbind#178

**Pull request closed without merging**
