### PR TITLE
Update gh-pages to v1.1.0

### PR DESCRIPTION
**Pull request by nicholaschuayunzhi**
Repositories now have their own dedicated cache.

Resolves https://github.com/MarkBind/markbind/issues/141

Tested:
image

### CODE REVIEW

**Review by acjh — APPROVED** [review]

**Comment by Gisonrg** [comment]
Did you test the publishing site using the updated library?

**Comment by nicholaschuayunzhi** [comment]
@Gisonrg, i had previously tested on a private repository but when i test again it seems to not be working on `v1.1.0` as well as `v0.12.0`. Im currently taking a look at it. https://github.com/nicholaschuayunzhi/markbind-test

EDIT: Also noted there is no more logger as of `v1.0.0` will see if there is a workaround.

**Comment by nicholaschuayunzhi** [comment]
The deploy works for v1.1.0. https://github.com/nicholaschuayunzhi/markbind-test/commit/21691a6547a707bafad04bc4ebed463f01a1897f

I was trying to deploy a site with no changes 😅 

However, there is still no <span>logger</span>, will look for a workaround for this PR.

**Comment by nicholaschuayunzhi** [comment]
@acjh @Gisonrg currently the work around suggested on the repo is to:

Windows:
`$ SET NODE_DEBUG=gh-pages&&markbind deploy`
Unix:
`$ NODE_DEBUG=gh-pages&&markbind deploy`

and I've set it programmatically in https://github.com/MarkBind/markbind-cli/pull/30/commits/d8485aebc8e67d481dc1cb0900bfa30299017bf3

to log:
```
GH-PAGES 16236: Cloning https://github.com/nicholaschuayunzhi/markbind-test.git into ..\markbind
-cli\node_modules\gh-pages\.cache\aHR0cHM6Ly9naXRodWIuY29tL25pY2hvbGFzY2h1YXl1bnpoaS9tYXJrYmluZC
10ZXN0LmdpdA
GH-PAGES 16236: Cleaning
GH-PAGES 16236: Fetching origin
GH-PAGES 16236: Checking out origin/gh-pages
GH-PAGES 16236: Removing files
GH-PAGES 16236: Copying files
GH-PAGES 16236: Adding all
GH-PAGES 16236: Committing
GH-PAGES 16236: Pushing
info: Deployed!
```

**Pull request merged**
